# Generated by Django 5.1.6 on 2025-03-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pizza_App", "0003_pizzasize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizzasize",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=1
            ),
        ),
    ]
