# Generated by Django 5.1.6 on 2025-05-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pizza_App", "0005_customer_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name="orderpizza",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Pizza_App.pizzasize",
            ),
        ),
        migrations.AddField(
            model_name="orderpizza",
            name="special_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="orderpizza",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_pizzas",
                to="Pizza_App.order",
            ),
        ),
        migrations.CreateModel(
            name="OrderPizzaTopping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizza_App.orderpizza",
                    ),
                ),
                (
                    "topping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizza_App.topping",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orderpizza",
            name="toppings",
            field=models.ManyToManyField(
                related_name="order_pizzas",
                through="Pizza_App.OrderPizzaTopping",
                to="Pizza_App.topping",
            ),
        ),
    ]
