# Generated by Django 5.1.5 on 2025-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pizza_App", "0006_topping_orderpizza_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("COMPLETED", "Completado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
