# Generated by Django 5.1.6 on 2025-06-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pizza_App", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="drink",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="drinks/"),
        ),
    ]
